export const classList = [
    "Hero",
    "Bandit",
    "Astrologer",
    "Warrior",
    "Prisoner",
    "Confessor",
    "Wretch",
    "Vagabond",
    "Prophet",
    "Samurai"  
]

export const weaponsList = [
    "Axes",
    "Bows or Crossbows",
    "Claws",
    "Daggers",
    "Colossal Weapons",
    "Fists",
    "Flails",
    "Staff",
    "Spears",
    "Greatswords",
    "Halberds",
    "Hammers",
    "Thrusting Weapons", 
    "Katanas",
    "Scythes",
    "Shields",
    "Straight Swords",
    "Whips",
    "Twinblades",
    "Catalyst",
    "Seal",
    "Curved Swords",
]

export const passiveList = [
    "Cant wear headpiece",
    "Armor must match",
    "No starting keepsake",
    "Cant change Ash of War",
    "Must light roll (<30% load)", 
    "Weapon must apply bleed buildup",
    "Cannot go above 30 vigor", 
    "Strength and dex must be equal",
    "Cannot level dex",
    "Cannot level str",
    "Same number of crimson/cerullean vials",
    "Only skeleton summons allowed",
    "Must keep starting Armor",
    "Cannot wear pants",
    "Only beast summons are allowed",
    "Not allowed to use shops",
    "Must keep 1 talisman slot empty",
    "Not allowed to recover runes", 
    "Can't pickup maps", 
    "Max soul level of 100", 
    "No summoning (players or ashes)",
    "Must aquire all great runes before end of game",
]
