export const classList = [
    "Hero",
    "Bandit",
    "Astrologer",
    "Warrior",
    "Prisoner",
    "Confessor",
    "Wretch",
    "Vagabond",
    "Prophet",
    "Samurai"  
]

export const weaponsList = [
    "Daggers",
    "Straight Swords",
    "Greatswords",
    "Colossal Swords",
    "Thrusting Weapons",
    "Heavy Thrusting Weapons",
    "Curved Swords",
    "Curved Greatswords",
    "Katanas",
    "Twinblades",
    "Axes",
    "Greataxes",
    "Hammers",
    "Flails",
    "Great Hammers",
    "Colossal Weapons",
    "Spears",
    "Great Spears",
    "Halberds",
    "Scythes",
    "Whips",
    "Fists",
    "Claws",
    "Light Bows",
    "Bows",
    "Greatbows",
    "Crossbows",
    "Ballistae",
    "Glintstone Staffs",
    "Sacred Seals"
    "Torches"
]

export const passiveList = [
    "Cant wear headpiece",
    "Armor must match",
    "No starting keepsake",
    "Cant change Ash of War",
    "Must light roll (<30% load)", 
    "Weapon must apply bleed buildup",
    "Cannot go above 30 vigor", 
    "Strength and dex must be equal",
    "Cannot level dex",
    "Cannot level str",
    "Same number of crimson/cerullean vials",
    "Only skeleton summons allowed",
    "Must keep starting Armor",
    "Cannot wear pants",
    "Only beast summons are allowed",
    "Not allowed to use shops",
    "Must keep 1 talisman slot empty",
    "Not allowed to recover runes", 
    "Can't pickup maps", 
    "Max soul level of 100", 
    "No summoning (players or ashes)",
    "Must aquire all great runes before end of game",
]
